#!/bin/python3

import os
from time import sleep
from pynput import keyboard

interval = 5
directory = "/media/pi/whitestore/wallpapers"
images = os.listdir(directory)

def on_q():
	exit()

l = keyboard.GlobalHotKeys({"<ctrl>+<alt>+q": on_q})
l.start()
l.join()

index = 0
while True:
	os.system(f"timeout {interval}s feh {directory}/{images[index]}")
	index += 1
	if index > len(images) - 1:
		index = 0

